[build]
  # Commande de build pour Vite avec résolution des dépendances
  command = "npm install --legacy-peer-deps && npm run build"
  # Dossier de sortie après build
  publish = "dist"

[build.environment]
  # Version Node.js
  NODE_VERSION = "18"

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les variables d'environnement
[context.production.environment]
  VITE_API_KEY = ""
  VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_API_KEY = ""
  VITE_ENVIRONMENT = "preview"
