[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'npm install',
    'cd server && npm install'
]

[phases.build]
cmds = [
    'npm run build',
    'cd server && npm run init-db'
]

[start]
cmd = 'cd server && npm start'
